name: Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Ensure image_generator exist on VPS
        uses: appleboy/ssh-action@master
        with:
          host: 192.162.69.217
          username: charles
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/charles/image_generator
           

     

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 192.162.69.217
          username: charles
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/charles/image_generator
            git pull
            deactivate || true
            source venv/bin/activate
            uvicorn main:app --reload --host 0.0.0.0 --port 8000